<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- NuGet metadata -->
    <PackageId>Mmb.KeePass</PackageId>
    <Version>0.1.0</Version>
    <Authors>mammothb</Authors>
    <Description>C# library for KeePass (.kdbx) databases</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/mammothb/Mmb.KeePass</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>keepass</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mmb.KeePass.Tests" />
  </ItemGroup>
</Project>
